spring:
  application:
    name: peminjaman-service
  datasource:
    url: jdbc:h2:file:./target/h2db/db/peminjamans;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: peminjaman.exchange
    listener:
      simple:
        default-requeue-rejected: false

app:
  rabbitmq-peminjaman:
    queue: peminjaman.queue
    exchange: peminjaman.exchange
    routing-key: peminjaman.routing.key
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "your email"
    from: "your email"
    password: "your password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    '[com.gio.rabbitmq_service]': DEBUG
    '[org.springframework.mail.javamail]': DEBUG
    '[jakarta.mail]': DEBUG