spring:
  application:
    name: rabbitmq-pengembalian
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: pengembalian.exchange
    listener:
      simple:
        default-requeue-rejected: false

app:
  rabbitmq-pengembalian:
    queue: pengembalian.queue
    exchange: pengembalian.exchange
    routing-key: pengembalian.routing.key
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "your email"
    from: "your email"
    password: "your password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

logging:
  level:
    '[com.gio.rabbitmq_service]': DEBUG
    '[org.springframework.mail.javamail]': DEBUG
    '[jakarta.mail]': DEBUG